# SPDX-FileCopyrightText: Copyright © 2024 - 2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

name: publish-to-maven-central
on:
  workflow_run:
    workflows: [full]
    types: [completed]
jobs:
  release-to-gh:
    timeout-minutes: 5
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch,'v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      IS_PUBLISHING: 1
      ORG_GRADLE_PROJECT_ghUsername: ${{ secrets.GITHUB_ACTOR }}
      ORG_GRADLE_PROJECT_ghPassword: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          filter: "blob:none"
          fetch-depth: 0
      - run: git remote set-head --auto origin
      - uses: actions/setup-java@v5.1.0
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v5.0.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - run: ./gradlew publishAllPublicationsToStagingRepository
      - run: |
          export STAGING=$(printf "%s" $(./gradlew stagingPath --quiet))
          gh release create ${{ github.event.workflow_run.head_branch }} --generate-notes $STAGING/* --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}
  publish-to-central:
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch,'v')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      IS_PUBLISHING: 1
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          filter: "blob:none"
          fetch-depth: 0
      - run: git remote set-head --auto origin
      - uses: actions/setup-java@v5.1.0
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v5.0.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - run: ./gradlew publishAllPublicationsToStagingRepository --scan --no-configuration-cache
      - uses: jreleaser/release-action@v2
      - run: jreleaser deploy --config-file jreleaser.yml
        env:
          JRELEASER_SONATYPE_USERNAME: ${{ secrets.CENTRAL_USER }}
          JRELEASER_SONATYPE_PASSWORD: ${{ secrets.CENTRAL_PASS }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSWORD }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.SIGNING_KEY }}
