# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

name: full
on:
  push:
    branches: &default [develop]
    tags:
      - v*
  pull_request:
    branches: *default
  workflow_call:
jobs:
  full:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          ref: ${{ github.ref }}
          filter: "blob:none"
          fetch-depth: 0
      - uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v5.0.2
        with:
          cache-read-only: true
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - run: ./gradlew build --console=plain --no-build-cache --no-configuration-cache --rerun-tasks
        env:
          ORG_GRADLE_PROJECT_ghUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_ghPassword: ${{ github.token }}
