# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

name: jreleaser
on:
  push:
    branches:
      - "**"
      - "!develop"
jobs:
  publish:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: write
      packages: write
    env:
      IS_PUBLISHING: true
      JRELEASER_LOG_LEVEL: debug
      JRELEASER_LOG_CONSOLE_LEVEL: debug
    steps:
      - uses: actions/checkout@v6.0.0
        with:
          # head sha is always the latest commit but head branch has the name we need for publishing
          filter: "blob:none"
          fetch-depth: 0
      # Ensure the remote default branch is set so tools relying on origin/HEAD behave consistently.
      - run: git remote set-head --auto origin
      - uses: actions/setup-java@v5.0.0
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v5.0.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - run: ./gradlew jreleaserConfig jreleaserFullRelease --deployer github --no-configuration-cache --console=plain --debug--scan
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
